# fly.toml app configuration file generated for summer-resonance-3072 on 2023-09-23T10:55:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "summer-resonance-3072"
primary_region = "sin"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
